### ISSUE TITLE
Failed to load Selenium

### ISSUE THREAD

**Issue by St33lMouse** [simbake/web_search#11]
selenium is installed, but it fails to load.

2023-11-03 10:46:04 ERROR:Failed to load the extension "web_search".
Traceback (most recent call last):
  File "/home/mouse/test/text-generation-webui/modules/extensions.py", line 36, in load_extensions
    exec(f"import extensions.{name}.script")
  File "<string>", line 1, in <module>
  File "/home/mouse/test/text-generation-webui/extensions/web_search/script.py", line 3, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'

any ideas? (Linux)

In other news, Brave is including a privacy oriented llama2 chatbot into the browser, should be out in a few days. It will be interesting to see how well it integrates with the browser. I imagine they'll go with the heavily aligned llama2 chat version to keep themselves out of trouble. You should check it out when it arrives, since using a local model gives the user unlimited, fast  usage without alignment. Your little extension is about to become more relevant, and I'll bet the brave integration will give you a lot of ideas.

**Comment by simbake** [comment]
You need to run cmd_linux.sh (In text-gen folder) in terminal and install selenium from there.
Thanks for the news, I didn't know about this.
