### ISSUE TITLE
I tried everything this just won't work

### ISSUE THREAD

**Issue by TheRealMiRRoRMaN** [simbake/web_search#19]
Won't work at all, tons of errors.

tons.

**Comment by LaernuTairos** [comment]
It works but it seems to be missing some steps for install
If you've already followed the steps listed >>>

Go into your text gen folder > launch Cmd_Windows.bat
do a simple       pip install selenium
go back into extensions\web_search
Re-do the pip install -r requirements.txt step

"now" you should be good. 

Not sure if installing chrome was actually required before installing selenium but I did it anyway

**Comment by TheRealMiRRoRMaN** [comment]
> It works but it seems to be missing some steps for install
>If you've already followed the steps listed >>>
>Go into your text gen folder > launch Cmd_Windows.bat
>do a simple pip install selenium
>go back into extensions\web_search
>Re-do the pip install -r requirements.txt step

>"now" you should be good.
>Not sure if installing chrome was actually required before installing selenium but I did it anyway

Gives:

`14:52:27-815670 ERROR    Failed to load the extension "web_search".
Traceback (most recent call last):
  File "D:\text-generation-webui\modules\extensions.py", line 36, in load_extensions
    exec(f"import extensions.{name}.script")
  File "<string>", line 1, in <module>
  File "D:\text-generation-webui\extensions\web_search\script.py", line 19, in <module>
    service = Service(ChromeDriverManager().install())
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\envs\textgen\Lib\site-packages\webdriver_manager\chrome.py", line 40, in install
    driver_path = self._get_driver_binary_path(self.driver)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\envs\textgen\Lib\site-packages\webdriver_manager\core\manager.py", line 40, in _get_driver_binary_path
    file = self._download_manager.download_file(driver.get_driver_download_url(os_type))
                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\envs\textgen\Lib\site-packages\webdriver_manager\drivers\chrome.py", line 32, in get_driver_download_url
    driver_version_to_download = self.get_driver_version_to_download()
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\envs\textgen\Lib\site-packages\webdriver_manager\core\driver.py", line 48, in get_driver_version_to_download
    return self.get_latest_release_version()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\envs\textgen\Lib\site-packages\webdriver_manager\drivers\chrome.py", line 64, in get_latest_release_version
    determined_browser_version = ".".join(determined_browser_version.split(".")[:3])
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'split'`

Brand-spanking-new version of Oobabooga too btw, updated just yesterday.

**Comment by TheRealMiRRoRMaN** [comment]
oh and I tried the threadpoolctl thing too. didn't work. at all. 

i'm open for suggestions.

**Comment by TheRealMiRRoRMaN** [comment]
Gives:

14:52:27-815670 ERROR Failed to load the extension "web_search". Traceback
(most recent call last): File
"D:\text-generation-webui\modules\extensions.py", line 36, in
load_extensions exec(f"import extensions.{name}.script") File "<string>",
line 1, in <module> File
"D:\text-generation-webui\extensions\web_search\script.py", line 19, in
<module> service = Service(ChromeDriverManager().install())
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File
"C:\ProgramData\anaconda3\envs\textgen\Lib\site-packages\webdriver_manager\chrome.py",
line 40, in install driver_path = self._get_driver_binary_path(self.driver)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File
"C:\ProgramData\anaconda3\envs\textgen\Lib\site-packages\webdriver_manager\core\manager.py",
line 40, in _get_driver_binary_path file =
self._download_manager.download_file(driver.get_driver_download_url(os_type))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File
"C:\ProgramData\anaconda3\envs\textgen\Lib\site-packages\webdriver_manager\drivers\chrome.py",
line 32, in get_driver_download_url driver_version_to_download =
self.get_driver_version_to_download() ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File
"C:\ProgramData\anaconda3\envs\textgen\Lib\site-packages\webdriver_manager\core\driver.py",
line 48, in get_driver_version_to_download return
self.get_latest_release_version() ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File
"C:\ProgramData\anaconda3\envs\textgen\Lib\site-packages\webdriver_manager\drivers\chrome.py",
line 64, in get_latest_release_version determined_browser_version =
".".join(determined_browser_version.split(".")[:3])
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ AttributeError: 'NoneType' object has no
attribute 'split'

Brand-spanking-new version of Oobabooga too btw, updated just yesterday.


oh and I tried the threadpoolctl thing too. didn't work. at all.

i'm open for suggestions.

**Comment by BioTox1n** [comment]
You need to install google chrome. It gives that error because it is searching for the chrome browser version but gets a NoneType since you don't have it installed.

**Comment by TheRealMiRRoRMaN** [comment]
well naturally, i did that too. but it doesn't work.
