### ISSUE TITLE
Unable to run the script with the latest commit

### ISSUE THREAD

**Issue by iChristGit** [simbake/web_search#6]
I get this when booting up, after git pull and installing requirements.

2023-09-01 13:33:50 INFO:Loading the extension "web_search"...
2023-09-01 13:33:50 ERROR:Failed to load the extension "web_search".
Traceback (most recent call last):
  File "D:\oobabooga_windows\text-generation-webui\modules\extensions.py", line 35, in load_extensions
    exec(f"import extensions.{name}.script")
  File "<string>", line 1, in <module>
  File "D:\oobabooga_windows\text-generation-webui\extensions\web_search\script.py", line 7, in <module>
    from requests_html import HTML
ModuleNotFoundError: No module named 'requests_html'

**Comment by simbake** [comment]
Hi, that happens when the module was not found in your python environment. Make sure to run requirements.txt in the webui environment. A quick fix is to run the webui cmd e.g cmd_linux.sh and install the module from there, do ``` pip install requests-html ```.
Make sure to always install requirement.txt in the oobaboga web ui python envrionment.

**Comment by simbake** [comment]
Will get back to you when I have pushed some fixes. You can revert to the older version in the releases for now.

**Comment by simbake** [comment]
Hi, please try the new update. Should work better than the previous commit. Make sure to run cmd file that came with text-gen-webui e.g cmd_linux.sh.
Then cd into extensions/webui and run pip install -r requirements.txt from there.

**Comment by iChristGit** [comment]
still some errors after fresh install + requirements, needed to install selenium and chromedriver-autoinstaller, now getting this:


2023-09-02 18:30:12 ERROR:Failed to load the extension "web_search".
Traceback (most recent call last):
  File "D:\oobabooga_windows\text-generation-webui\modules\extensions.py", line 35, in load_extensions
    exec(f"import extensions.{name}.script")
  File "<string>", line 1, in <module>
  File "D:\oobabooga_windows\text-generation-webui\extensions\web_search\script.py", line 12, in <module>
    chromedriver_autoinstaller.install()
  File "D:\oobabooga_windows\installer_files\env\lib\site-packages\chromedriver_autoinstaller\__init__.py", line 21, in install
    chromedriver_filepath = utils.download_chromedriver(path, no_ssl)
  File "D:\oobabooga_windows\installer_files\env\lib\site-packages\chromedriver_autoinstaller\utils.py", line 263, in download_chromedriver
    chrome_version = get_chrome_version()
  File "D:\oobabooga_windows\installer_files\env\lib\site-packages\chromedriver_autoinstaller\utils.py", line 170, in get_chrome_version
    dirs = [f.name for f in os.scandir("C:\\Program Files\\Google\\Chrome\\Application") if f.is_dir() and re.match("^[0-9.]+$", f.name)]
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Program Files\\Google\\Chrome\\Application'

**Comment by iChristGit** [comment]
Edit: I forgot I removed chrome, re-installed and now getting this:

WARNING:Can not find chromedriver for currently installed chrome version.

**Comment by simbake** [comment]
I think I was also getting the same warning. Ignore and try searching something.

**Comment by gregrobison** [comment]
I have the same issue running on several devices and it prevents the extension from working.

**Comment by tijo95** [comment]
I also have this error, tested on 2 PCs


2023-09-09 18:27:42 ERROR:Failed to load the extension "web_search".
Traceback (most recent call last):
  File "C:\Users\wutan\OneDrive\Bureau\oobabooga_windows\text-generation-webui\modules\extensions.py", line 35, in load_extensions
    exec(f"import extensions.{name}.script")
  File "<string>", line 1, in <module>
  File "C:\Users\wutan\OneDrive\Bureau\oobabooga_windows\text-generation-webui\extensions\web_search\script.py", line 3, in <module>
    import chromedriver_autoinstaller
ModuleNotFoundError: No module named 'chromedriver_autoinstaller'

**Comment by tijo95** [comment]
I have found a solution for those who have the problem of the module 'chromedriver_autoinstaller':
identify the location of the module and put its direct path in the script.py file with web_search extension as below:

import sys
sys.path.append(r'C:\Users\wutan\AppData\Local\Programs\Python\Python310\Lib\site-packages')

import gradio as gr
import modules.shared as shared
import chromedriver_autoinstaller
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.chrome.service import Service
import urllib

**Comment by simbake** [comment]
Sorry guys for this, I will be away for a while. My grandma was sick and unfortunately she passed away. I will fix this when I get back. How you all understand and many thanks to you all.

**Comment by luisernestopoland** [comment]
Hi, I got this error: "urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)> ". Any help will be appreciated. Thank you

**Comment by simbake** [comment]
Hi everyone, please test out the new commit. Thanks.

**Comment by Dartvauder** [comment]
> Hi everyone, please test out the new commit. Thanks.
> 

All works fine now. Thank you!

**Comment by simbake** [comment]
Closing this now. You can reopen is the issue occurs again
