### ISSUE TITLE
Search only works once.

### ISSUE THREAD

**Issue by HAV0X1014** [simbake/web_search#9]
After using this extension for a while, the search function has seemed to stop working. It produces this output when it attempts to search. I have tried this on the webui and through the API (I mainly use the API) and this occurs on both. I have Opera, Opera Beta, and Google Chrome browsers installed on a Pop os 22.04 install.  

```
127.0.0.1 - - [15/Oct/2023 12:26:36] "POST /api/v1/chat HTTP/1.1" 200 -
----------------------------------------
Exception occurred during processing of request from ('127.0.0.1', 32970)
Traceback (most recent call last):
  File "/home/hav0x/Downloads/text-generation-webui/installer_files/env/lib/python3.10/socketserver.py", line 683, in process_request_thread
    self.finish_request(request, client_address)
  File "/home/hav0x/Downloads/text-generation-webui/installer_files/env/lib/python3.10/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/hav0x/Downloads/text-generation-webui/installer_files/env/lib/python3.10/socketserver.py", line 747, in __init__
    self.handle()
  File "/home/hav0x/Downloads/text-generation-webui/installer_files/env/lib/python3.10/http/server.py", line 433, in handle
    self.handle_one_request()
  File "/home/hav0x/Downloads/text-generation-webui/installer_files/env/lib/python3.10/http/server.py", line 421, in handle_one_request
    method()
  File "/home/hav0x/Downloads/text-generation-webui/extensions/api/blocking_api.py", line 89, in do_POST
    for a in generator:
  File "/home/hav0x/Downloads/text-generation-webui/modules/chat.py", line 297, in generate_chat_reply
    for history in chatbot_wrapper(text, state, regenerate=regenerate, _continue=_continue, loading_message=loading_message):
  File "/home/hav0x/Downloads/text-generation-webui/modules/chat.py", line 207, in chatbot_wrapper
    text = apply_extensions('input', text, state, is_chat=True)
  File "/home/hav0x/Downloads/text-generation-webui/modules/extensions.py", line 224, in apply_extensions
    return EXTENSION_MAP[typ](*args, **kwargs)
  File "/home/hav0x/Downloads/text-generation-webui/modules/extensions.py", line 82, in _apply_string_extensions
    text = func(*args, **kwargs)
  File "/home/hav0x/Downloads/text-generation-webui/extensions/web_search/script.py", line 52, in input_modifier
    search_data = google_results(query,state)
  File "/home/hav0x/Downloads/text-generation-webui/extensions/web_search/script.py", line 21, in google_results
    driver = webdriver.Chrome(service=service,options=options)
  File "/home/hav0x/Downloads/text-generation-webui/installer_files/env/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/home/hav0x/Downloads/text-generation-webui/installer_files/env/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py", line 53, in __init__
    self.service.start()
  File "/home/hav0x/Downloads/text-generation-webui/installer_files/env/lib/python3.10/site-packages/selenium/webdriver/common/service.py", line 98, in start
    self._start_process(self._path)
  File "/home/hav0x/Downloads/text-generation-webui/installer_files/env/lib/python3.10/site-packages/selenium/webdriver/common/service.py", line 204, in _start_process
    self.process = subprocess.Popen(
  File "/home/hav0x/Downloads/text-generation-webui/installer_files/env/lib/python3.10/subprocess.py", line 837, in __init__
    errread, errwrite) = self._get_handles(stdin, stdout, stderr)
  File "/home/hav0x/Downloads/text-generation-webui/installer_files/env/lib/python3.10/subprocess.py", line 1638, in _get_handles
    c2pwrite = stdout.fileno()
ValueError: I/O operation on closed file
----------------------------------------


```

**Comment by simbake** [comment]
Hi, its currently late here. I will have a look at it tomorrow.

**Comment by Tomlanny** [comment]
I'm having same issue. I love the integration and would love to see it work.

**Comment by simbake** [comment]
Hi all, I have tried to replicate the issue but could not, I am on windows bdwy. Maybe more details of your system might help.
- Selenium version
- Chrome version
- webui version.
- Does it work once or not at all?
- Did it used to work but lately it doesn't? Might be an update to something broke things.

**Comment by Tomlanny** [comment]
Selenium version: 4.14.0
Chrome version:  Version 118.0.5993.89 (Official Build) (64-bit)
webui version: v1.7
Does it work once or not at all? Sometimes once
Did it used to work but lately it doesn't? Might be an update to something
broke things.: It never worked since I started using it five days ago.
here is the error code:
Traceback (most recent call last):
  File
"C:\Users\tomla\miniconda3\envs\textgen\lib\site-packages\gradio\queueing.py",
line 406, in call_prediction
    output = await route_utils.call_process_api(
  File
"C:\Users\tomla\miniconda3\envs\textgen\lib\site-packages\gradio\route_utils.py",
line 226, in call_process_api
    output = await app.get_blocks().process_api(
  File
"C:\Users\tomla\miniconda3\envs\textgen\lib\site-packages\gradio\blocks.py",
line 1554, in process_api
    result = await self.call_function(
  File
"C:\Users\tomla\miniconda3\envs\textgen\lib\site-packages\gradio\blocks.py",
line 1206, in call_function
    prediction = await utils.async_iteration(iterator)
  File
"C:\Users\tomla\miniconda3\envs\textgen\lib\site-packages\gradio\utils.py",
line 517, in async_iteration
    return await iterator.__anext__()
  File
"C:\Users\tomla\miniconda3\envs\textgen\lib\site-packages\gradio\utils.py",
line 510, in __anext__
    return await anyio.to_thread.run_sync(
  File
"C:\Users\tomla\miniconda3\envs\textgen\lib\site-packages\anyio\to_thread.py",
line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File
"C:\Users\tomla\miniconda3\envs\textgen\lib\site-packages\anyio\_backends\_asyncio.py",
line 877, in run_sync_in_worker_thread
    return await future
  File
"C:\Users\tomla\miniconda3\envs\textgen\lib\site-packages\anyio\_backends\_asyncio.py",
line 807, in run
    result = context.run(func, *args)
  File
"C:\Users\tomla\miniconda3\envs\textgen\lib\site-packages\gradio\utils.py",
line 493, in run_sync_iterator_async
    return next(iterator)
  File
"C:\Users\tomla\miniconda3\envs\textgen\lib\site-packages\gradio\utils.py",
line 647, in gen_wrapper
    yield from f(*args, **kwargs)
  File "C:\text-generation-webui\modules\chat.py", line 329, in
generate_chat_reply_wrapper
    for i, history in enumerate(generate_chat_reply(text, state,
regenerate, _continue, loading_message=True)):
  File "C:\text-generation-webui\modules\chat.py", line 297, in
generate_chat_reply
    for history in chatbot_wrapper(text, state, regenerate=regenerate,
_continue=_continue, loading_message=loading_message):
  File "C:\text-generation-webui\modules\chat.py", line 207, in
chatbot_wrapper
    text = apply_extensions('input', text, state, is_chat=True)
  File "C:\text-generation-webui\modules\extensions.py", line 224, in
apply_extensions
    return EXTENSION_MAP[typ](*args, **kwargs)
  File "C:\text-generation-webui\modules\extensions.py", line 82, in
_apply_string_extensions
    text = func(*args, **kwargs)
  File "C:\text-generation-webui\extensions\web_search\script.py", line 52,
in input_modifier
    search_data = google_results(query,state)
  File "C:\text-generation-webui\extensions\web_search\script.py", line 21,
in google_results
    driver = webdriver.Chrome(service=service,options=options)
  File
"C:\Users\tomla\miniconda3\envs\textgen\lib\site-packages\selenium\webdriver\chrome\webdriver.py",
line 45, in __init__
    super().__init__(
  File
"C:\Users\tomla\miniconda3\envs\textgen\lib\site-packages\selenium\webdriver\chromium\webdriver.py",
line 53, in __init__
    self.service.start()
  File
"C:\Users\tomla\miniconda3\envs\textgen\lib\site-packages\selenium\webdriver\common\service.py",
line 98, in start
    self._start_process(self._path)
  File
"C:\Users\tomla\miniconda3\envs\textgen\lib\site-packages\selenium\webdriver\common\service.py",
line 204, in _start_process
    self.process = subprocess.Popen(
  File "C:\Users\tomla\miniconda3\envs\textgen\lib\subprocess.py", line
837, in __init__
    errread, errwrite) = self._get_handles(stdin, stdout, stderr)
  File "C:\Users\tomla\miniconda3\envs\textgen\lib\subprocess.py", line
1304, in _get_handles
    c2pwrite = msvcrt.get_osfhandle(stdout.fileno())
ValueError: I/O operation on closed file

**Comment by HAV0X1014** [comment]
Selenium version: 4.14.0
Chrome version:  Version 118.0.5993.70
Webui version: 1.7
Works once for API, sometimes not at all for API. WebUI is consistent with working or not working.
It worked before when I was using this on my CPU. Ever since I started using my GPU (RX 7900xtx) as the server, it has given this issue. It worked for the API and the WebUI before.
I have reinstalled the WebUI and the extensiona few times in the past few weeks, but it did not change the extension working/not working.

**Comment by simbake** [comment]
Hi all. Please checkout the new update that fixes this issue. I found the new selenium update to be the issue so reverted to 4.13.0, I also disabled gpu acceleration on the chrome headless. This should not affect the normal chrome.

Please update and install requirements.txt again as you did when installing. This will automatically downgrade you to a working version.

**Comment by HAV0X1014** [comment]
It is working now after this update on the API and webui! Thank you so much!

**Comment by simbake** [comment]
You are welcome. Have fun.
You can reopen if you encounter something similar.
